runtime: nodejs12
instance_class: F2
service: default
resources:
  memory_gb: 2

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(css|js|png|ico))$
    static_files: build/\1
    upload: build/.*\.(css|js|png|ico)$

  - url: /.*
    secure: always
    static_files: build/index.html
    upload: build/index.html